"""Creative generation -- the first half of the self-testing creative loop.

For a chosen intervention + segment + occasion (+ optional product), this
produces several candidate ad creatives, each a distinct *angle* (urgency,
value, aspiration, ...). Copy is written by Groq (reusing llm._chat, with a
deterministic template fallback); the ad image is generated by Pollinations.ai
-- free, keyless, returns a plain URL the frontend loads directly, so there is
no image quota to exhaust and nothing to store server-side.

Phase 2 (pre_test.py) scores these variants against synthetic personas and
picks a winner before the Execution agent sends anything.
"""
from __future__ import annotations

import hashlib
import json
import urllib.parse

import llm

POLLINATIONS = "https://image.pollinations.ai/prompt/{prompt}"

# The angles we ask for, in priority order. Each candidate creative takes one.
ANGLES = ["Urgency", "Value", "Aspiration"]

_CACHE: dict[str, list[dict]] = {}


def _seed(*parts: str) -> int:
    return int(hashlib.sha1("|".join(parts).encode()).hexdigest()[:8], 16) % 100_000


def image_prompt(product_name: str | None, occasion_theme: str | None,
                 segment_label: str, angle: str) -> str:
    subject = product_name or "premium Indian fashion apparel"
    scene = occasion_theme or "elegant seasonal lifestyle"
    mood = {
        "Urgency": "bold high-contrast lighting, dynamic energy",
        "Value": "bright clean catalog lighting, approachable",
        "Aspiration": "cinematic editorial lighting, luxurious",
    }.get(angle, "editorial lighting")
    return (
        f"Premium e-commerce marketing ad photograph for {subject}, themed around "
        f"{scene}, {mood}, styled for {segment_label} shoppers, Indian fashion, "
        f"high detail, professional product photography, no text, no watermark"
    )


def image_url(prompt: str, seed: int, w: int = 768, h: int = 512) -> str:
    q = urllib.parse.quote(prompt)
    return (POLLINATIONS.format(prompt=q) +
            f"?width={w}&height={h}&seed={seed}&nologo=true&model=flux")


def _copy_variants(intervention_label: str, segment_label: str, occasion_theme: str | None,
                   product_name: str | None, first_name: str | None, n: int) -> list[dict]:
    """Ask Groq for n distinct ad-copy angles in one call; fall back to templates."""
    angles = ANGLES[:n]
    occ = f" Occasion theme: {occasion_theme}." if occasion_theme else ""
    prod = f" Featured item: {product_name}." if product_name else ""
    who = f" Addressed to {first_name}." if first_name else ""
    system = (
        "You are a senior performance-marketing copywriter for an Indian fashion brand. "
        "Write short, native-feeling ad copy. No markdown, no hype words like 'guarantee' "
        "or '100% certain'. Respond ONLY with a JSON array."
    )
    user = (
        f"Intervention: {intervention_label}. Segment: {segment_label}.{occ}{prod}{who}\n"
        f"Write {len(angles)} ad-copy variants, one per angle: {', '.join(angles)}.\n"
        'Each variant: {"angle": <angle>, "headline": <max 6 words>, "body": <1 sentence>}.\n'
        "Return a JSON array of exactly these variants, in this angle order."
    )
    raw = llm._chat(system, user, max_tokens=300, temperature=0.8)
    if raw:
        try:
            txt = raw.strip()
            if txt.startswith("```"):
                txt = txt.strip("`").lstrip("json").strip()
            data = json.loads(txt)
            out = []
            for i, angle in enumerate(angles):
                item = data[i] if i < len(data) else {}
                head = str(item.get("headline", "")).strip()
                body = str(item.get("body", "")).strip()
                if head or body:
                    out.append({"angle": angle, "headline": head, "body": body, "copy_source": "ai"})
            if len(out) == len(angles):
                return out
        except Exception as exc:  # noqa: BLE001
            print(f"[creative] copy parse failed, using fallback: {exc}")

    # Deterministic fallback copy per angle.
    nm = first_name or "there"
    item = product_name or "your pick"
    occ_word = occasion_theme or "the season"
    templates = {
        "Urgency": ("Almost gone", f"Hi {nm}, {item} is still in your cart - finish before it sells out."),
        "Value": ("A little something off", f"Hi {nm}, here's a small discount to complete {item} today."),
        "Aspiration": (f"Made for {occ_word}", f"Hi {nm}, {item} was picked to match your style for {occ_word}."),
    }
    return [{"angle": a, "headline": templates[a][0], "body": templates[a][1], "copy_source": "template"}
            for a in angles]


def generate_variants(intervention_key: str, intervention_label: str, segment_label: str,
                      occasion_theme: str | None = None, product_name: str | None = None,
                      first_name: str | None = None, n: int = 3) -> list[dict]:
    """Return n candidate creatives: {id, angle, headline, body, copy, copy_source,
    image_prompt, image_url}. Cached per (intervention, segment, occasion, product)."""
    n = max(1, min(n, len(ANGLES)))
    ck = "|".join([intervention_key, segment_label, occasion_theme or "", product_name or "", str(n)])
    if ck in _CACHE:
        return _CACHE[ck]

    copies = _copy_variants(intervention_label, segment_label, occasion_theme, product_name, first_name, n)
    variants = []
    for i, c in enumerate(copies):
        prompt = image_prompt(product_name, occasion_theme, segment_label, c["angle"])
        seed = _seed(ck, c["angle"], str(i))
        copy_text = (c["headline"] + " - " + c["body"]).strip(" -") if c["headline"] else c["body"]
        variants.append({
            "id": f"v{i+1}",
            "angle": c["angle"],
            "headline": c["headline"],
            "body": c["body"],
            "copy": copy_text,
            "copy_source": c["copy_source"],
            "image_prompt": prompt,
            "image_url": image_url(prompt, seed),
        })
    _CACHE[ck] = variants
    return variants
