import jsPDF from "jspdf";
import { Plan } from "./api";

// jsPDF's built-in Helvetica has no rupee glyph, so use "Rs" + en-IN grouping.
const rs = (x: number) => "Rs " + Math.round(x).toLocaleString("en-IN");

export function exportPlanPdf(plan: Plan, analyst: string | null) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 40;
  let y = 50;

  doc.setFont("helvetica", "bold"); doc.setFontSize(20); doc.setTextColor(20, 24, 40);
  doc.text("Foresight - Spend Plan", M, y);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(120);
  doc.text(new Date().toLocaleString(), W - M, y, { align: "right" });
  y += 12; doc.setDrawColor(220); doc.line(M, y, W - M, y); y += 26;

  doc.setFontSize(11);
  const metrics: [string, string][] = [
    ["Budget", rs(plan.budget)],
    ["Predicted incremental revenue", `${rs(plan.pred_incr_revenue)}  (90% CI ${rs(plan.pred_incr_revenue_ci[0])} - ${rs(plan.pred_incr_revenue_ci[1])})`],
    ["Blended ROAS", `${plan.blended_roi}x`],
    ["Incremental conversions", `+${Math.round(plan.pred_incr_conversions).toLocaleString("en-IN")}`],
  ];
  metrics.forEach(([k, v]) => {
    doc.setTextColor(110); doc.text(`${k}:`, M, y);
    doc.setTextColor(20, 24, 40); doc.text(v, M + 185, y); y += 18;
  });
  y += 8;

  if (analyst) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(90);
    doc.text("AI Analyst brief", M, y); y += 14;
    doc.setFont("helvetica", "normal"); doc.setTextColor(50);
    const lines = doc.splitTextToSize(analyst, W - 2 * M) as string[];
    doc.text(lines, M, y); y += lines.length * 13 + 14;
  }

  // Allocation table (hand-laid, no plugin dependency).
  const cols = [M, 168, 300, 360, 432, 528];
  doc.setFillColor(124, 131, 251); doc.rect(M, y - 11, W - 2 * M, 18, "F");
  doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(255, 255, 255);
  ["Segment", "Channel", "Reach", "Cost", "Pred. revenue", "ROAS"].forEach((h, i) => doc.text(h, cols[i], y + 1));
  y += 20;
  doc.setFont("helvetica", "normal"); doc.setTextColor(40, 44, 60);
  plan.plan.forEach((p, idx) => {
    if (idx % 2 === 1) { doc.setFillColor(244, 245, 250); doc.rect(M, y - 11, W - 2 * M, 16, "F"); }
    const row = [p.segment_label, p.intervention_label, p.reach_funded.toLocaleString("en-IN"),
      rs(p.cost), rs(p.pred_incr_revenue), `${p.roi}x`];
    row.forEach((c, i) => doc.text(String(c), cols[i], y));
    y += 16;
  });
  y += 18;

  const bl = plan.baselines, inc = plan.incrementality;
  doc.setFontSize(10); doc.setTextColor(30, 120, 90);
  doc.text(`vs naive allocation: +${bl.uplift_vs_even_pct}% more revenue than an even split (+${rs(bl.uplift_vs_even_abs)} for the same spend).`, M, y); y += 16;
  doc.setTextColor(60, 70, 200);
  doc.text(`Incrementality (held-out control): predicted ${rs(inc.predicted_incr_revenue)} vs actual ${rs(inc.actual_incr_revenue)} - ${inc.accuracy}% accurate.`, M, y);

  doc.setFontSize(8); doc.setTextColor(150);
  doc.text("Generated by Foresight - budget optimization + incrementality proof + NVIDIA-pool AI analyst", M, H - 28);

  doc.save("foresight-spend-plan.pdf");
}
